# Generated by Django 5.1.2 on 2024-11-11 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_user_city_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
